### PR TITLE
Bump Microsoft.ServiceFabric.* from 7.1.1541 to 7.1.1951

### PR DESCRIPTION
**Pull request by abatishchev**

### CODE REVIEW

**Comment by loekd** [comment]
Looks like the build is falling during the install of sf. I'll have to look into that.
It seems like an issue in the MS provided script.

**Comment by abatishchev** [comment]
@loekd I'm trying to debug the error.

First, I found this https://github.com/PowerShell/PowerShell/issues/19833
But then I found a good explanatory of what's going on in here: https://github.com/PowerShell/PowerShell/issues/19833

And indeed, the GitHub workflow task runs powershell.exe (PS for Windows) instead of pwsh.exe (PS Core)

**Comment by abatishchev** [comment]
Can you permitting running workflows to a group of contributors and add me to it?

**Comment by abatishchev** [comment]
Hey @loekd,
I asked advice on Discord, see https://discord.com/channels/180528040881815552/1122099214944571452/1231643499506565151
Link to join: https://discord.gg/powershell

**Comment by abatishchev** [comment]
Success! It made progress to the next step.

Can you please check why it fails? I wonder why does it need an snk file in the first place?

**Comment by loekd** [comment]
I've been asked to sign the package. I am using a self signed certificate for that. Injecting the password from the environment.

**Review by loekd — APPROVED** [review]

**Comment by abatishchev** [comment]
Yay!!

**Comment by loekd** [comment]
Thanks for all your help @abatishchev !
The new version is live now.

**Comment by abatishchev** [comment]
Thank _you_! I'm trying it in my internal project now.

**Pull request merged**
