### PR TITLE
refactored MockActorProxyFactory to allow multiple actors with different types to have the same ActorId

### LINKED ISSUE #5: MockActorProxyFactory can't support an ActorId being assigned to multiple actor instances, but different types.
It's perfectly valid to do something like this:

```csharp
var actorId = new ActorId(some_guid);
var actor_1 = _actorProxyFactory.CreateActorProxy<IMyActorType>(actorId);
var actor_2 = _actorProxyFactory.CreateActorProxy<IMyOtherActorType>(actorId);
```

but `MockActorProxyFactory` expects a single instance of `IActor` for each `ActorId` and so this scenario can't be mocked.

### PR DESCRIPTION
**Pull request by moswald**
Fixes #5 by changing the `ConcurrentDictionary` to store collections of actors instead of a single actor.

### CODE REVIEW

**Comment by WonderPanda** [comment]
I'm wondering if the ConcurrentBag is unnecessary overhead. The outer ConcurrentDictionary already provides thread safety for modifying it's internal contents so could this not be simplified to just be a List?

**Comment by moswald** [comment]
That's a good point; I didn't think that all the way through.

**Comment by loekd** [comment]
It would be much more efficient to use `ActorId `and `Actor ` Type combined as key, instead of using a HashSet as value.

**Comment by moswald** [comment]
Glad I could help!

**Pull request merged**
