### PR TITLE
Upgraded nuget packages (SF 2.6.210)

### PR DESCRIPTION
**Pull request by Marusyk**
We always use the latest version of SF. After upgrade we can't use your package because it is using SF 2.6.206. So, this PR will upgrade SF packages in this project. Please review.

### CODE REVIEW

**Comment by Marusyk** [comment]
What do you think about that?

**Comment by loekd** [comment]
Sorry it took some time. We had a couple of holidays here, and I have a busy job.
I've just created v2.1.0 which has the latest packages. It should appear on nuget shortly.

Thanks for the PR!
In your next PR, please upgrade the package version with a minor tick if there are no breaking changes. And add a line to the readme.md, stating 'upgraded to SF version x'. 
Doing so will allow me to simply accept the PR, which will automatically trigger the release of a new package.

**Comment by Marusyk** [comment]
Ok, thanks. But why didn't you accept my PR? I can fix version with a minor  tick. I didn't know about that because you haven't any info for collaborations in readme. So, why the PR is not accepted?

**Comment by loekd** [comment]
My bad.

**Pull request closed without merging**
