### PR TITLE
Upgraded to new SDK (SF 3.3.638)

### PR DESCRIPTION
**Pull request by ThiemeNL**
No code changes and unit tests are passing.

### CODE REVIEW

**Comment by adam8690** [comment]
You beat us to it! We were making the same changes today so we can use the latest SF version. Thanks

**Comment by loekd** [comment]
@ThiemeNL thanks for your contribution! @adam8690 thanks for the good intentions.

**Comment by loekd** [comment]
Having some trouble with a test that fails in the Azure DevOps pipeline...

**Comment by loekd** [comment]
Fixed, merged and released!

**Comment by ThiemeNL** [comment]
Thanks @loekd, we appreciate your work!

**Pull request merged**
