### PR TITLE
Updated Microsoft.ServiceFabric.Actors 6.0.1017

### PR DESCRIPTION
**Pull request by jcwrequests**
Implemented new GetRemindersAsync method

### CODE REVIEW

**Comment by ThiemeNL** [comment]
I had exactly the same issue with the new SF SDK version, so thank you very much!

I think loekd will ask you to update the package version and add a line to the readme.md.
See the contribute notes in the readme file.

**Comment by jcwrequests** [comment]
@ThiemeNL Thanks for the information. I will make an update to ensure I following the contribution rules. Looks the change broke some tests which I will have to look into. I am not sure if there is a test that covers the change. At work I had the need to for this because we are going to be upgrading to the latest version of SF so I thought I could help with a PR.

**Comment by jcwrequests** [comment]
I just realized the tests are probably failing because my personal system doesn't have SF installed. So I may have an update a bit sooner.

**Comment by jcwrequests** [comment]
I had to fix Fixed MockQueryServiceFactory due to new internal parameter added to the constructor for `System.Fabric.Query.StatelessService`. The new parameter is `System.Fabric.Query.ServiceMetadata serviceMetadata` which I just pass default and now all the tests are passing. I should have checked that the first time and installed SF on my local machine but it's all functioning now.

**Comment by esbenbach** [comment]
@loekd Now we only need you to approve it, merge it and publish a new package ;)

**Comment by loekd** [comment]
thanks for the heads-up, I'd missed this one :-)
pipeline is running

**Pull request merged**
