### PR TITLE
Service Move/Election Testing

### PR DESCRIPTION
**Pull request by charleszipp**
This adds mock classes that we have been using in our project to unit test service move conditions. We have been discussing open sourcing what we have with msft and the asf product group and they suggested I add this to your library. 

This allows from a unit test to orchestrate the creation, deletion, promotion, and demotion of replicas within a service. The mock replica set will invoke the same operations as service fabric runtime which allows for testing the state of the service after moves happen. 

In our project we manage both reliable state (shared among all replicas) and in-memory state thats local to only a single replica. This unit testing has been extremely useful in ensuring we are managing that state appropriately in an automated way. 

This allows us to write specflow tests like the following. The "occupied" aspect is specific to the internals of our service so feel free to ignore that.
```
Scenario: occupied stateful service primary changed to new node
	Given stateful service named "fabric:/MyApp/MyService/0007d06a-a2da-442f-9711-5e498bc6e42f" is created
	And a new replica is created as "Primary" with id "111"
	When stateful service is occupied with instance name "2c5601c1-2bd9-4cd4-8813-99072483cae2"
	And a new replica is created as "IdleSecondary" with id "222"
	And the idle secondary replica is promoted to active secondary
	And the active secondary replica is promoted to primary
	And the replica "111" is deleted
	Then the stateful service should be occupied with name "2c5601c1-2bd9-4cd4-8813-99072483cae2" and type uri "fabric:/MyApp/MyService/0007d06a-a2da-442f-9711-5e498bc6e42f"
	And replica "222" should be "Primary"
```
The .Shift project is necessary because unfortunately nothing in the service fabric sdk allows you to interrogate the current role of the replica. The mocking aspect really only needs to know the what the current role is so im open/flexible to trimming this down and changing how its tied in with the mocking. I have this library in another github project thats private for the moment so this could be swapped for nuget dependency as well.

I am under no impression that this PR is complete. However, I wanted to offer a first chance pass to see if you are open to incorporating this into your library before I commit more time to this.

### CODE REVIEW

**Comment by charleszipp** [comment]
@loekd Ryan McIntyre from msft will reach out to you. He is a

**Comment by charleszipp** [comment]
Good suggestion loek. I was hoping to sever the dependency to Shift as its not really intended for mocking specifically. I was only including this temporarily to get a successful build. We just need a way to track the role and I believe i can drop the dependency. I like the suggestion about using the `MockReliableStateManager`. I hadnt thought about using it for that purpose. I always look for ways to use composition as opposed to inheritance as well (hence the ReplicaContext class in shift library). I think your suggestion should be able to allow injecting the object that owns this state rather than only having access via inheritance.

**Comment by charleszipp** [comment]
@loekd i have removed the dependency on shift in the latest commit.

I did not actually need to use the state manager at all to track the role. I already had a wrapper class around the stateful service `MockStatefulServiceReplica` that represents the service running on an individual replica. I used this to track the role. 
I also added methods to encapsulate the operations a replica performs during different role change events. There are probably more that can/need to be added. However, these are the ones I needed when writing our tests.
This was originally 100% owned by the replica set. However, I felt the replica should really own this behavior. The replica set should only own how to orchestrate operations involving multiple replicas (i.e. primary elections).
This approach also meant that neither the replica set or replica have any direct dependency on the state manager. This should make them easier to setup in the tests.
I will work on adding some sample tests. Please let me know if there are any changes you would like me to make to whats there.
While I didnt end up doing the exact suggestion, it sparked some ideas that greatly simplified what was there before!

**Comment by charleszipp** [comment]
@loekd 
I have added two unit tests that execute role changes.
To demonstrate the concept, i added a in-memory stateful object to `MyStatefulService`. This object represents how someone may use a in-memory model to facilitate more complex queries/aggregations of data backed by a reliable collection. In this example, only the Primary replica should have this object populated. The tests perform role changes and assert that only the primary has this object populated.

One secondary issue I encountered is that the current implementation of the MockReliableStateManager and mock reliable collections do not provide a good way to share a single instance of the backing collection across all replicas. In my current project, we make the Dictionary behind the MockReliableDictionary a singleton that is injected into the state manager. This allows each replica to keep its own instance of the state manager but, the backing store is shared between all replicas. This is more closely aligned to what i have observed happens at runtime on the cluster. For now, i worked around this by using a single instance of the state manager and injecting that into each replica. The side effect however is that properties in the state manager tied to the replica, such as the Role are not accurate since its being shared between all replicas

**Comment by loekd** [comment]
Looking good so far. Do you have more commits coming in, or can we start reviewing and merging this?

**Comment by charleszipp** [comment]
@loekd we can start reviewing and merging

**Comment by charleszipp** [comment]
@loekd I am working on a contribution to the service fabric documentation around unit testing and a sample app to demonstrate. Is there anyway you could generate a new alpha or beta nuget package that includes these changes. Alternatively, i can use a direct assembly reference but, at some point i will need to update that to a nuget package before submitting it back to the service fabric team.

**Comment by loekd** [comment]
@charleszipp v3.3.0 contains the bits from this PR. Can't wait to read your article!
If you want, we can work on the issue mentioned above too.

> One secondary issue I encountered is that the current implementation of the MockReliableStateManager and mock reliable collections do not provide a good way to share a single instance of the backing collection across all replicas.

**Pull request merged**
